'use client';

import { create } from 'zustand';

// ─── Types ────────────────────────────────────────────────────────────────────

export type SetupStatus = 'watching' | 'triggered' | 'win' | 'loss' | 'missed' | 'invalid';
export type SmartMoneyBias = 'bullish' | 'bearish' | 'neutral';
export type LevelType = 'resistance' | 'support';
export type LevelStrength = 'strong' | 'moderate' | 'weak';
export type SetupDirection = 'bullish' | 'bearish';

export interface SetupCondition {
    id: string;
    text: string;
    checked: boolean;
}

export interface TradeSetup {
    id: string;
    name: string;        // 'Resistance Breakout', 'Support Bounce', etc.
    direction: SetupDirection;
    entry: number;
    targets: number[];   // [T1, T2, T3]
    stop: number;
    rr: number;          // risk/reward (auto-calculated)
    conditions: SetupCondition[];
    exitStrategy: string[];
    status: SetupStatus;
    notes?: string;
}

export interface KeyLevel {
    id: string;
    price: number;
    label: string;       // 'R1', 'R2', 'S1', etc.
    type: LevelType;
    strength: LevelStrength;
}

export interface SetupCard {
    id: string;
    date: string;          // YYYY-MM-DD
    symbol: string;
    currentPrice?: number;
    priceChangePct?: number;
    priceChangeDollar?: number;
    smartMoneyBias: SmartMoneyBias;
    bullishSetups: TradeSetup[];
    bearishSetups: TradeSetup[];
    keyLevels: KeyLevel[];
    sessionNotes?: string;
    isAutoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

// ─── Store Shape ──────────────────────────────────────────────────────────────

interface SetupState {
    // cards grouped by date: { 'YYYY-MM-DD': SetupCard[] }
    cardsByDate: Record<string, SetupCard[]>;

    // Actions — cards
    addCard: (card: Omit<SetupCard, 'id' | 'createdAt' | 'updatedAt'>) => string;
    updateCard: (id: string, updates: Partial<SetupCard>) => void;
    deleteCard: (id: string) => void;

    // Actions — setups within a card
    addSetup: (cardId: string, setup: Omit<TradeSetup, 'id'>) => void;
    updateSetup: (cardId: string, setupId: string, updates: Partial<TradeSetup>) => void;
    deleteSetup: (cardId: string, setupId: string) => void;
    toggleCondition: (cardId: string, setupId: string, conditionId: string) => void;

    // Actions — key levels
    addLevel: (cardId: string, level: Omit<KeyLevel, 'id'>) => void;
    deleteLevel: (cardId: string, levelId: string) => void;

    // Hydrate from localStorage
    hydrate: () => void;

    // Helpers
    getCardsForDate: (date: string) => SetupCard[];
    getDates: () => string[];  // sorted desc
}

// ─── Persistence helpers ──────────────────────────────────────────────────────

const STORAGE_KEY = 'tradepilot_setups_v1';

function load(): Record<string, SetupCard[]> {
    if (typeof window === 'undefined') return {};
    try {
        const raw = localStorage.getItem(STORAGE_KEY);
        return raw ? JSON.parse(raw) : {};
    } catch { return {}; }
}

function persist(cardsByDate: Record<string, SetupCard[]>) {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(cardsByDate)); } catch { }
}

function uid() {
    return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

// Find card across all dates
function findCard(cardsByDate: Record<string, SetupCard[]>, id: string): { date: string; card: SetupCard } | null {
    for (const [date, cards] of Object.entries(cardsByDate)) {
        const card = cards.find(c => c.id === id);
        if (card) return { date, card };
    }
    return null;
}

function mapCard(
    cardsByDate: Record<string, SetupCard[]>,
    id: string,
    fn: (card: SetupCard) => SetupCard
): Record<string, SetupCard[]> {
    const found = findCard(cardsByDate, id);
    if (!found) return cardsByDate;
    return {
        ...cardsByDate,
        [found.date]: cardsByDate[found.date].map(c => c.id === id ? fn(c) : c),
    };
}

// ─── Store ────────────────────────────────────────────────────────────────────

export const useSetupStore = create<SetupState>((set, get) => ({
    cardsByDate: {},

    hydrate: () => set({ cardsByDate: load() }),

    // ── Cards ──────────────────────────────────────────────────────────────────

    addCard: (data) => {
        const id = `sc-${uid()}`;
        const now = new Date().toISOString();
        const card: SetupCard = { ...data, id, createdAt: now, updatedAt: now };
        set(state => {
            const existing = state.cardsByDate[data.date] || [];
            const cardsByDate = { ...state.cardsByDate, [data.date]: [card, ...existing] };
            persist(cardsByDate);
            return { cardsByDate };
        });
        return id;
    },

    updateCard: (id, updates) => {
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, id, c => ({
                ...c, ...updates, updatedAt: new Date().toISOString(),
            }));
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    deleteCard: (id) => {
        set(state => {
            const found = findCard(state.cardsByDate, id);
            if (!found) return state;
            const remaining = state.cardsByDate[found.date].filter(c => c.id !== id);
            const cardsByDate = { ...state.cardsByDate };
            if (remaining.length === 0) {
                delete cardsByDate[found.date];
            } else {
                cardsByDate[found.date] = remaining;
            }
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    // ── Setups within a card ───────────────────────────────────────────────────

    addSetup: (cardId, setupData) => {
        const setup: TradeSetup = { ...setupData, id: `ts-${uid()}` };
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, cardId, c => ({
                ...c,
                bullishSetups: setup.direction === 'bullish' ? [...c.bullishSetups, setup] : c.bullishSetups,
                bearishSetups: setup.direction === 'bearish' ? [...c.bearishSetups, setup] : c.bearishSetups,
                updatedAt: new Date().toISOString(),
            }));
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    updateSetup: (cardId, setupId, updates) => {
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, cardId, c => {
                const updateList = (list: TradeSetup[]) =>
                    list.map(s => s.id === setupId ? { ...s, ...updates } : s);
                return {
                    ...c,
                    bullishSetups: updateList(c.bullishSetups),
                    bearishSetups: updateList(c.bearishSetups),
                    updatedAt: new Date().toISOString(),
                };
            });
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    deleteSetup: (cardId, setupId) => {
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, cardId, c => ({
                ...c,
                bullishSetups: c.bullishSetups.filter(s => s.id !== setupId),
                bearishSetups: c.bearishSetups.filter(s => s.id !== setupId),
                updatedAt: new Date().toISOString(),
            }));
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    toggleCondition: (cardId, setupId, conditionId) => {
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, cardId, c => {
                const toggle = (list: TradeSetup[]) =>
                    list.map(s => s.id === setupId
                        ? {
                            ...s,
                            conditions: s.conditions.map(cd =>
                                cd.id === conditionId ? { ...cd, checked: !cd.checked } : cd
                            ),
                        }
                        : s
                    );
                return {
                    ...c,
                    bullishSetups: toggle(c.bullishSetups),
                    bearishSetups: toggle(c.bearishSetups),
                    updatedAt: new Date().toISOString(),
                };
            });
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    // ── Key Levels ─────────────────────────────────────────────────────────────

    addLevel: (cardId, levelData) => {
        const level: KeyLevel = { ...levelData, id: `kl-${uid()}` };
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, cardId, c => ({
                ...c,
                keyLevels: [...c.keyLevels, level].sort((a, b) => b.price - a.price),
                updatedAt: new Date().toISOString(),
            }));
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    deleteLevel: (cardId, levelId) => {
        set(state => {
            const cardsByDate = mapCard(state.cardsByDate, cardId, c => ({
                ...c,
                keyLevels: c.keyLevels.filter(l => l.id !== levelId),
                updatedAt: new Date().toISOString(),
            }));
            persist(cardsByDate);
            return { cardsByDate };
        });
    },

    // ── Helpers ────────────────────────────────────────────────────────────────

    getCardsForDate: (date) => get().cardsByDate[date] || [],

    getDates: () =>
        Object.keys(get().cardsByDate).sort((a, b) => b.localeCompare(a)),
}));
