'use client';

import React, { useState, useEffect, useMemo } from 'react';
import {
    Plus, X, ChevronRight, Crosshair, TrendingUp, TrendingDown,
    Minus, Check, Trash2, Edit3, ChevronDown, ChevronUp,
    Zap, Calendar, Target, AlertCircle, CheckCircle2,
    BarChart2, ArrowUpRight, ArrowDownLeft, Sparkles,
    Clock, DollarSign, Activity,
} from 'lucide-react';
import clsx from 'clsx';
import {
    useSetupStore,
    SetupCard, TradeSetup, KeyLevel,
    SmartMoneyBias, SetupStatus, SetupDirection, LevelType, LevelStrength,
} from '@/store/setupStore';

// ─── Helpers ──────────────────────────────────────────────────────────────────

const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 2 }).format(n);

const fmtP = (n: number) =>
    `${n >= 0 ? '+' : ''}${n.toFixed(2)}`;

function calcRR(entry: number, stop: number, target: number): number {
    const risk = Math.abs(entry - stop);
    const reward = Math.abs(target - entry);
    return risk > 0 ? parseFloat((reward / risk).toFixed(2)) : 0;
}

function formatDate(iso: string): string {
    const d = new Date(iso + 'T00:00:00');
    const today = new Date();
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    if (iso === today.toISOString().slice(0, 10)) return 'Today';
    if (iso === yesterday.toISOString().slice(0, 10)) return 'Yesterday';
    return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
}

function todayISO() {
    return new Date().toISOString().slice(0, 10);
}

// ─── Status styling ───────────────────────────────────────────────────────────

const statusConfig: Record<SetupStatus, { label: string; color: string; dot: string }> = {
    watching: { label: 'Watching', color: 'text-sky-400 bg-sky-500/10 border-sky-500/20', dot: 'bg-sky-400' },
    triggered: { label: 'Triggered', color: 'text-amber-400 bg-amber-500/10 border-amber-500/20', dot: 'bg-amber-400 animate-pulse' },
    win: { label: 'Win', color: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20', dot: 'bg-emerald-400' },
    loss: { label: 'Loss', color: 'text-rose-400 bg-rose-500/10 border-rose-500/20', dot: 'bg-rose-400' },
    missed: { label: 'Missed', color: 'text-zinc-400 bg-zinc-500/10 border-zinc-500/20', dot: 'bg-zinc-400' },
    invalid: { label: 'Invalid', color: 'text-zinc-600 bg-zinc-800/50 border-zinc-700/30', dot: 'bg-zinc-600' },
};

const biasConfig: Record<SmartMoneyBias, { label: string; color: string; bg: string; icon: React.ElementType }> = {
    bullish: { label: 'BULLISH', color: 'text-emerald-400', bg: 'bg-emerald-500/15 border-emerald-500/30', icon: TrendingUp },
    bearish: { label: 'BEARISH', color: 'text-rose-400', bg: 'bg-rose-500/15 border-rose-500/30', icon: TrendingDown },
    neutral: { label: 'NEUTRAL', color: 'text-amber-400', bg: 'bg-amber-500/15 border-amber-500/30', icon: Minus },
};

// ─── Create Card Modal ────────────────────────────────────────────────────────

interface CreateCardForm {
    symbol: string;
    date: string;
    currentPrice: string;
    smartMoneyBias: SmartMoneyBias;
    sessionNotes: string;
}

function CreateCardModal({ onClose }: { onClose: () => void }) {
    const { addCard } = useSetupStore();
    const [form, setForm] = useState<CreateCardForm>({
        symbol: '',
        date: todayISO(),
        currentPrice: '',
        smartMoneyBias: 'neutral',
        sessionNotes: '',
    });

    const handle = (k: keyof CreateCardForm, v: string) =>
        setForm(f => ({ ...f, [k]: v }));

    const submit = () => {
        if (!form.symbol.trim()) return;
        addCard({
            symbol: form.symbol.trim().toUpperCase(),
            date: form.date,
            currentPrice: form.currentPrice ? parseFloat(form.currentPrice) : undefined,
            smartMoneyBias: form.smartMoneyBias,
            sessionNotes: form.sessionNotes || undefined,
            bullishSetups: [],
            bearishSetups: [],
            keyLevels: [],
            isAutoGenerated: false,
        });
        onClose();
    };

    const inputCls = 'w-full px-3 py-2 rounded-xl border border-white/10 bg-white/[0.04] text-zinc-100 text-sm placeholder:text-zinc-600 focus:outline-none focus:ring-2 focus:ring-emerald-500/30 focus:border-emerald-500/40 transition-all';

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
            <div className="relative w-full max-w-md mx-4 rounded-2xl border border-white/10 bg-[#1A1F2E] shadow-2xl">
                <div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-white/5">
                    <div>
                        <h2 className="text-base font-bold text-zinc-100 flex items-center gap-2">
                            <Crosshair className="h-4 w-4 text-emerald-400" />
                            New Setup Card
                        </h2>
                        <p className="text-xs text-zinc-500 mt-0.5">Create a trade setup card for a ticker</p>
                    </div>
                    <button onClick={onClose} className="text-zinc-500 hover:text-zinc-300 p-1 rounded-lg hover:bg-white/5 transition-colors">
                        <X className="h-5 w-5" />
                    </button>
                </div>

                <div className="px-6 py-4 space-y-4">
                    <div className="grid grid-cols-2 gap-3">
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Ticker Symbol *</label>
                            <input className={inputCls} placeholder="SPY" value={form.symbol}
                                onChange={e => handle('symbol', e.target.value.toUpperCase())} />
                        </div>
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Date</label>
                            <input type="date" className={inputCls} value={form.date}
                                onChange={e => handle('date', e.target.value)} />
                        </div>
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-1 block">Current Price (optional)</label>
                        <input className={inputCls} type="number" step="0.01" placeholder="0.00"
                            value={form.currentPrice} onChange={e => handle('currentPrice', e.target.value)} />
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-2 block">Smart Money Bias</label>
                        <div className="grid grid-cols-3 gap-2">
                            {(['bullish', 'neutral', 'bearish'] as SmartMoneyBias[]).map(bias => {
                                const cfg = biasConfig[bias];
                                const Icon = cfg.icon;
                                return (
                                    <button key={bias} onClick={() => handle('smartMoneyBias', bias)}
                                        className={clsx(
                                            'py-2.5 rounded-xl text-sm font-medium border flex items-center justify-center gap-1.5 transition-all',
                                            form.smartMoneyBias === bias ? `${cfg.bg} ${cfg.color}` : 'bg-white/[0.03] border-white/10 text-zinc-500 hover:text-zinc-300'
                                        )}>
                                        <Icon className="h-3.5 w-3.5" />
                                        <span className="capitalize">{bias}</span>
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-1 block">Session Notes (optional)</label>
                        <textarea className={clsx(inputCls, 'resize-none h-16')}
                            placeholder="Key context, catalysts, macro bias..."
                            value={form.sessionNotes} onChange={e => handle('sessionNotes', e.target.value)} />
                    </div>
                </div>

                <div className="px-6 pb-5 flex gap-3">
                    <button onClick={onClose} className="flex-1 py-2.5 rounded-xl border border-white/10 text-zinc-400 hover:text-zinc-200 text-sm transition-all">
                        Cancel
                    </button>
                    <button onClick={submit} disabled={!form.symbol.trim()}
                        className="flex-1 py-2.5 rounded-xl bg-emerald-500 text-[#181B24] font-semibold text-sm hover:bg-emerald-400 transition-all disabled:opacity-40">
                        Create Card
                    </button>
                </div>
            </div>
        </div>
    );
}

// ─── Add Setup Modal ──────────────────────────────────────────────────────────

interface SetupForm {
    name: string;
    direction: SetupDirection;
    entry: string;
    t1: string;
    t2: string;
    t3: string;
    stop: string;
    conditions: string;
    exitStrategy: string;
}

function AddSetupModal({ cardId, onClose }: { cardId: string; onClose: () => void }) {
    const { addSetup } = useSetupStore();
    const [form, setForm] = useState<SetupForm>({
        name: '', direction: 'bullish', entry: '', t1: '', t2: '', t3: '', stop: '',
        conditions: '', exitStrategy: '',
    });

    const handle = (k: keyof SetupForm, v: string) => setForm(f => ({ ...f, [k]: v }));

    const entry = parseFloat(form.entry) || 0;
    const stop = parseFloat(form.stop) || 0;
    const t1 = parseFloat(form.t1) || 0;
    const rr = entry && stop && t1 ? calcRR(entry, stop, t1) : 0;

    const submit = () => {
        if (!form.name.trim() || !entry || !stop || !t1) return;
        const targets = [t1, parseFloat(form.t2) || 0, parseFloat(form.t3) || 0].filter(Boolean);
        const conditionList = form.conditions.split('\n').filter(Boolean).map(text => ({
            id: `c-${Date.now()}-${Math.random().toString(36).slice(2)}`,
            text: text.trim(),
            checked: false,
        }));
        const exitList = form.exitStrategy.split('\n').filter(Boolean).map(s => s.trim());
        addSetup(cardId, {
            name: form.name.trim(),
            direction: form.direction,
            entry,
            targets,
            stop,
            rr,
            conditions: conditionList,
            exitStrategy: exitList,
            status: 'watching',
        });
        onClose();
    };

    const inputCls = 'w-full px-3 py-2 rounded-xl border border-white/10 bg-white/[0.04] text-zinc-100 text-sm placeholder:text-zinc-600 focus:outline-none focus:ring-2 focus:ring-emerald-500/30 focus:border-emerald-500/40 transition-all';
    const isLong = form.direction === 'bullish';

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
            <div className="relative w-full max-w-lg mx-4 rounded-2xl border border-white/10 bg-[#1A1F2E] shadow-2xl max-h-[90vh] overflow-y-auto">
                <div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-white/5 sticky top-0 bg-[#1A1F2E] z-10">
                    <h2 className="text-base font-bold text-zinc-100">Add Trade Setup</h2>
                    <button onClick={onClose} className="text-zinc-500 hover:text-zinc-300 p-1 rounded-lg hover:bg-white/5">
                        <X className="h-5 w-5" />
                    </button>
                </div>

                <div className="px-6 py-4 space-y-4">
                    {/* Direction toggle */}
                    <div className="grid grid-cols-2 gap-2">
                        {(['bullish', 'bearish'] as SetupDirection[]).map(d => (
                            <button key={d} onClick={() => handle('direction', d)}
                                className={clsx(
                                    'py-2.5 rounded-xl border text-sm font-semibold flex items-center justify-center gap-2 transition-all',
                                    form.direction === d
                                        ? d === 'bullish'
                                            ? 'bg-emerald-500/20 border-emerald-500/40 text-emerald-400'
                                            : 'bg-rose-500/20 border-rose-500/40 text-rose-400'
                                        : 'bg-white/[0.03] border-white/10 text-zinc-500 hover:text-zinc-300'
                                )}>
                                {d === 'bullish' ? <ArrowUpRight className="h-4 w-4" /> : <ArrowDownLeft className="h-4 w-4" />}
                                {d === 'bullish' ? 'Bullish Setup' : 'Bearish Setup'}
                            </button>
                        ))}
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-1 block">Setup Name *</label>
                        <input className={inputCls} placeholder="e.g. Resistance Breakout" value={form.name}
                            onChange={e => handle('name', e.target.value)} />
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">{isLong ? 'Buy' : 'Sell'} Entry *</label>
                            <input className={inputCls} type="number" step="0.01" placeholder="0.00"
                                value={form.entry} onChange={e => handle('entry', e.target.value)} />
                        </div>
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Stop Loss *</label>
                            <input className={inputCls} type="number" step="0.01" placeholder="0.00"
                                value={form.stop} onChange={e => handle('stop', e.target.value)} />
                        </div>
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Target 1 *</label>
                            <input className={inputCls} type="number" step="0.01" placeholder="0.00"
                                value={form.t1} onChange={e => handle('t1', e.target.value)} />
                        </div>
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Target 2</label>
                            <input className={inputCls} type="number" step="0.01" placeholder="Optional"
                                value={form.t2} onChange={e => handle('t2', e.target.value)} />
                        </div>
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Target 3</label>
                            <input className={inputCls} type="number" step="0.01" placeholder="Optional"
                                value={form.t3} onChange={e => handle('t3', e.target.value)} />
                        </div>
                        <div>
                            {rr > 0 && (
                                <div className={clsx(
                                    'h-full flex flex-col items-center justify-center rounded-xl border p-2',
                                    rr >= 2 ? 'bg-emerald-500/10 border-emerald-500/30' : rr >= 1 ? 'bg-amber-500/10 border-amber-500/30' : 'bg-rose-500/10 border-rose-500/30'
                                )}>
                                    <span className="text-[11px] text-zinc-500">R:R Ratio</span>
                                    <span className={clsx('text-lg font-bold mt-0.5', rr >= 2 ? 'text-emerald-400' : rr >= 1 ? 'text-amber-400' : 'text-rose-400')}>
                                        {rr}:1
                                    </span>
                                </div>
                            )}
                        </div>
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-1 block">Entry Conditions (one per line)</label>
                        <textarea className={clsx(inputCls, 'resize-none h-24')}
                            placeholder={'Wait for price above VWAP\nVolume > 20-day average\nRSI >50 momentum confirmation'}
                            value={form.conditions} onChange={e => handle('conditions', e.target.value)} />
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-1 block">Exit Strategy (one per line)</label>
                        <textarea className={clsx(inputCls, 'resize-none h-20')}
                            placeholder={'Stop if price drops 1% below entry\nTake 75% off at T1, rest at T2\nExit at market close if not at T1'}
                            value={form.exitStrategy} onChange={e => handle('exitStrategy', e.target.value)} />
                    </div>
                </div>

                <div className="px-6 pb-5 flex gap-3 sticky bottom-0 bg-[#1A1F2E] pt-2 border-t border-white/5">
                    <button onClick={onClose} className="flex-1 py-2.5 rounded-xl border border-white/10 text-zinc-400 text-sm transition-all">Cancel</button>
                    <button onClick={submit} disabled={!form.name.trim() || !entry || !stop || !t1}
                        className={clsx(
                            'flex-1 py-2.5 rounded-xl font-semibold text-sm transition-all disabled:opacity-40',
                            form.direction === 'bullish'
                                ? 'bg-emerald-500 text-[#181B24] hover:bg-emerald-400'
                                : 'bg-rose-500 text-white hover:bg-rose-400'
                        )}>
                        Add {form.direction === 'bullish' ? 'Bullish' : 'Bearish'} Setup
                    </button>
                </div>
            </div>
        </div>
    );
}

// ─── Add Level Modal ──────────────────────────────────────────────────────────

function AddLevelModal({ cardId, onClose }: { cardId: string; onClose: () => void }) {
    const { addLevel } = useSetupStore();
    const [price, setPrice] = useState('');
    const [label, setLabel] = useState('');
    const [type, setType] = useState<LevelType>('resistance');
    const [strength, setStrength] = useState<LevelStrength>('moderate');

    const submit = () => {
        const p = parseFloat(price);
        if (!p || !label.trim()) return;
        addLevel(cardId, { price: p, label: label.trim(), type, strength });
        onClose();
    };

    const inputCls = 'w-full px-3 py-2 rounded-xl border border-white/10 bg-white/[0.04] text-zinc-100 text-sm placeholder:text-zinc-600 focus:outline-none focus:ring-2 focus:ring-emerald-500/30 focus:border-emerald-500/40 transition-all';

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
            <div className="relative w-full max-w-sm mx-4 rounded-2xl border border-white/10 bg-[#1A1F2E] shadow-2xl">
                <div className="flex items-center justify-between px-6 pt-5 pb-4 border-b border-white/5">
                    <h2 className="text-base font-bold text-zinc-100">Add Key Level</h2>
                    <button onClick={onClose} className="text-zinc-500 hover:text-zinc-300 p-1"><X className="h-5 w-5" /></button>
                </div>

                <div className="px-6 py-4 space-y-4">
                    <div className="grid grid-cols-2 gap-3">
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Price *</label>
                            <input className={inputCls} type="number" step="0.01" placeholder="0.00"
                                value={price} onChange={e => setPrice(e.target.value)} />
                        </div>
                        <div>
                            <label className="text-xs text-zinc-500 mb-1 block">Label *</label>
                            <input className={inputCls} placeholder="R1, S2, Gap..." value={label}
                                onChange={e => setLabel(e.target.value)} />
                        </div>
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-2 block">Type</label>
                        <div className="grid grid-cols-2 gap-2">
                            {(['resistance', 'support'] as LevelType[]).map(t => (
                                <button key={t} onClick={() => setType(t)}
                                    className={clsx('py-2 rounded-xl border text-sm font-medium capitalize transition-all',
                                        type === t
                                            ? t === 'resistance' ? 'bg-rose-500/20 border-rose-500/30 text-rose-400' : 'bg-emerald-500/20 border-emerald-500/30 text-emerald-400'
                                            : 'bg-white/[0.03] border-white/10 text-zinc-500 hover:text-zinc-300'
                                    )}>{t}</button>
                            ))}
                        </div>
                    </div>

                    <div>
                        <label className="text-xs text-zinc-500 mb-2 block">Strength</label>
                        <div className="grid grid-cols-3 gap-2">
                            {(['strong', 'moderate', 'weak'] as LevelStrength[]).map(s => (
                                <button key={s} onClick={() => setStrength(s)}
                                    className={clsx('py-2 rounded-xl border text-xs font-medium capitalize transition-all',
                                        strength === s ? 'bg-blue-500/20 border-blue-500/30 text-blue-300' : 'bg-white/[0.03] border-white/10 text-zinc-500 hover:text-zinc-300'
                                    )}>{s}</button>
                            ))}
                        </div>
                    </div>
                </div>

                <div className="px-6 pb-5 flex gap-3">
                    <button onClick={onClose} className="flex-1 py-2.5 rounded-xl border border-white/10 text-zinc-400 text-sm">Cancel</button>
                    <button onClick={submit} disabled={!price || !label.trim()}
                        className="flex-1 py-2.5 rounded-xl bg-blue-500 text-white font-semibold text-sm hover:bg-blue-400 transition-all disabled:opacity-40">
                        Add Level
                    </button>
                </div>
            </div>
        </div>
    );
}

// ─── Setup Row (within card columns) ─────────────────────────────────────────

function SetupRow({
    setup, cardId, currentPrice,
}: { setup: TradeSetup; cardId: string; currentPrice?: number }) {
    const { updateSetup, deleteSetup, toggleCondition } = useSetupStore();
    const [expanded, setExpanded] = useState(false);
    const isLong = setup.direction === 'bullish';
    const sc = statusConfig[setup.status];

    return (
        <div className={clsx(
            'rounded-xl border transition-all duration-200',
            isLong ? 'border-emerald-500/15 bg-emerald-500/[0.03]' : 'border-rose-500/15 bg-rose-500/[0.03]'
        )}>
            {/* Header */}
            <div className="px-3 py-2.5">
                <div className="flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2 min-w-0">
                        <div className={clsx('w-1.5 h-1.5 rounded-full flex-shrink-0', sc.dot)} />
                        <span className={clsx('text-sm font-semibold truncate', isLong ? 'text-emerald-300' : 'text-rose-300')}>
                            {setup.name}
                        </span>
                    </div>
                    <div className="flex items-center gap-1 flex-shrink-0">
                        <span className={clsx('text-[10px] font-medium px-1.5 py-0.5 rounded-full border', sc.color)}>
                            {sc.label}
                        </span>
                        <button onClick={() => setExpanded(e => !e)}
                            className="text-zinc-600 hover:text-zinc-300 p-0.5 rounded transition-colors">
                            {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
                        </button>
                    </div>
                </div>

                {/* Price levels */}
                <div className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1">
                    <div>
                        <span className="text-[10px] text-zinc-600 uppercase tracking-wider">Entry</span>
                        <p className="text-sm font-mono font-semibold text-zinc-200">${setup.entry.toFixed(2)}</p>
                    </div>
                    <div>
                        <span className="text-[10px] text-zinc-600 uppercase tracking-wider">Stop</span>
                        <p className="text-sm font-mono font-semibold text-rose-400">${setup.stop.toFixed(2)}</p>
                    </div>
                    {setup.targets.map((t, i) => (
                        <div key={i}>
                            <span className="text-[10px] text-zinc-600 uppercase tracking-wider">T{i + 1}</span>
                            <p className="text-sm font-mono font-semibold text-emerald-400">${t.toFixed(2)}</p>
                        </div>
                    ))}
                    <div>
                        <span className="text-[10px] text-zinc-600 uppercase tracking-wider">R:R</span>
                        <p className={clsx('text-sm font-bold', setup.rr >= 2 ? 'text-emerald-400' : setup.rr >= 1 ? 'text-amber-400' : 'text-rose-400')}>
                            {setup.rr}:1
                        </p>
                    </div>
                </div>
            </div>

            {/* Expanded section */}
            {expanded && (
                <div className="border-t border-white/5 px-3 py-3 space-y-3">
                    {/* Conditions checklist */}
                    {setup.conditions.length > 0 && (
                        <div>
                            <p className="text-[10px] uppercase tracking-wider text-zinc-600 mb-2">Entry Conditions</p>
                            <div className="space-y-1.5">
                                {setup.conditions.map(c => (
                                    <button key={c.id} onClick={() => toggleCondition(cardId, setup.id, c.id)}
                                        className="w-full flex items-start gap-2 text-left group">
                                        <div className={clsx(
                                            'w-4 h-4 rounded border flex-shrink-0 mt-0.5 flex items-center justify-center transition-all',
                                            c.checked ? 'bg-emerald-500 border-emerald-500' : 'border-white/20 group-hover:border-white/40'
                                        )}>
                                            {c.checked && <Check className="h-2.5 w-2.5 text-[#181B24]" />}
                                        </div>
                                        <span className={clsx('text-xs leading-relaxed transition-colors',
                                            c.checked ? 'text-zinc-500 line-through' : 'text-zinc-300'
                                        )}>
                                            {c.text}
                                        </span>
                                    </button>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Exit strategy */}
                    {setup.exitStrategy.length > 0 && (
                        <div>
                            <p className="text-[10px] uppercase tracking-wider text-zinc-600 mb-2">Exit Strategy</p>
                            <div className="space-y-1">
                                {setup.exitStrategy.map((s, i) => (
                                    <p key={i} className="text-xs text-zinc-400 flex gap-1.5">
                                        <span className="text-zinc-600 flex-shrink-0">›</span>{s}
                                    </p>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Status picker */}
                    <div>
                        <p className="text-[10px] uppercase tracking-wider text-zinc-600 mb-2">Status</p>
                        <div className="flex flex-wrap gap-1">
                            {(Object.keys(statusConfig) as SetupStatus[]).map(s => {
                                const cfg = statusConfig[s];
                                return (
                                    <button key={s} onClick={() => updateSetup(cardId, setup.id, { status: s })}
                                        className={clsx(
                                            'px-2 py-0.5 rounded text-[10px] font-medium border transition-all',
                                            setup.status === s ? cfg.color : 'text-zinc-600 border-zinc-700/50 bg-transparent hover:text-zinc-400'
                                        )}>
                                        {cfg.label}
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    {/* Delete */}
                    <button onClick={() => deleteSetup(cardId, setup.id)}
                        className="w-full text-xs text-rose-500 hover:text-rose-400 flex items-center justify-center gap-1 py-1 rounded-lg hover:bg-rose-500/10 transition-colors">
                        <Trash2 className="h-3 w-3" /> Delete Setup
                    </button>
                </div>
            )}
        </div>
    );
}

// ─── Key Levels Visualizer ────────────────────────────────────────────────────

function KeyLevelsPanel({ card }: { card: SetupCard }) {
    const { deleteLevel, addLevel } = useSetupStore();
    const [showAdd, setShowAdd] = useState(false);

    const resistance = card.keyLevels.filter(l => l.type === 'resistance').sort((a, b) => b.price - a.price);
    const support = card.keyLevels.filter(l => l.type === 'support').sort((a, b) => b.price - a.price);

    const allPrices = card.keyLevels.map(l => l.price);
    if (card.currentPrice) allPrices.push(card.currentPrice);
    const maxPrice = allPrices.length ? Math.max(...allPrices) * 1.002 : 0;
    const minPrice = allPrices.length ? Math.min(...allPrices) * 0.998 : 0;
    const range = maxPrice - minPrice || 1;

    function barWidth(strength: LevelStrength) {
        return strength === 'strong' ? '90%' : strength === 'moderate' ? '65%' : '40%';
    }

    function pct(price: number) {
        return Math.max(0, Math.min(100, ((price - minPrice) / range) * 100));
    }

    const LevelRow = ({ level }: { level: KeyLevel }) => {
        const isRes = level.type === 'resistance';
        return (
            <div className="flex items-center gap-2 group">
                <span className="text-[10px] uppercase tracking-wider text-zinc-600 w-6 text-right flex-shrink-0">
                    {level.label}
                </span>
                <div className="flex-1 h-4 flex items-center">
                    <div
                        className={clsx('h-2 rounded-full transition-all duration-700', isRes ? 'bg-rose-500/60' : 'bg-emerald-500/60')}
                        style={{ width: barWidth(level.strength) }}
                    />
                </div>
                <span className="font-mono text-xs text-zinc-300 w-16 text-right">${level.price.toFixed(2)}</span>
                <button onClick={() => deleteLevel(card.id, level.id)}
                    className="opacity-0 group-hover:opacity-100 text-zinc-700 hover:text-rose-400 transition-all p-0.5">
                    <X className="h-3 w-3" />
                </button>
            </div>
        );
    };

    return (
        <div className="flex flex-col h-full">
            <div className="flex items-center justify-between mb-3">
                <span className="text-[10px] uppercase tracking-widest text-zinc-500 font-semibold">Key Levels</span>
                <button onClick={() => setShowAdd(true)}
                    className="flex items-center gap-1 text-[10px] text-blue-400 hover:text-blue-300 transition-colors">
                    <Plus className="h-3 w-3" /> Add
                </button>
            </div>

            {showAdd && <AddLevelModal cardId={card.id} onClose={() => setShowAdd(false)} />}

            {card.keyLevels.length === 0 ? (
                <div className="flex-1 flex items-center justify-center">
                    <div className="text-center">
                        <BarChart2 className="h-8 w-8 text-zinc-700 mx-auto mb-2" />
                        <p className="text-xs text-zinc-600">No levels yet</p>
                        <button onClick={() => setShowAdd(true)}
                            className="mt-2 text-xs text-blue-400 hover:text-blue-300 transition-colors">Add first level</button>
                    </div>
                </div>
            ) : (
                <div className="flex-1 space-y-1 overflow-visible">
                    {/* Resistance */}
                    {resistance.length > 0 && (
                        <div className="mb-3">
                            <p className="text-[9px] uppercase tracking-widest text-rose-500/70 mb-1.5 font-semibold">Resistance</p>
                            <div className="space-y-1.5">
                                {resistance.map(l => <LevelRow key={l.id} level={l} />)}
                            </div>
                        </div>
                    )}

                    {/* Current price line */}
                    {card.currentPrice && (
                        <div className="flex items-center gap-2 py-1">
                            <span className="text-[10px] text-sky-400 uppercase tracking-wider w-6 text-right flex-shrink-0">Now</span>
                            <div className="flex-1 h-px bg-sky-400/60 relative">
                                <div className="absolute right-0 top-1/2 -translate-y-1/2 w-1.5 h-1.5 rounded-full bg-sky-400" />
                            </div>
                            <span className="font-mono text-xs font-bold text-sky-400 w-16 text-right">${card.currentPrice.toFixed(2)}</span>
                            <div className="w-3.5" />
                        </div>
                    )}

                    {/* Support */}
                    {support.length > 0 && (
                        <div className="mt-3">
                            <p className="text-[9px] uppercase tracking-widest text-emerald-500/70 mb-1.5 font-semibold">Support</p>
                            <div className="space-y-1.5">
                                {support.map(l => <LevelRow key={l.id} level={l} />)}
                            </div>
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}

// ─── Setup Card ───────────────────────────────────────────────────────────────

function SetupCardView({ card }: { card: SetupCard }) {
    const { deleteCard, updateCard } = useSetupStore();
    const [showAddSetup, setShowAddSetup] = useState(false);
    const [menuOpen, setMenuOpen] = useState(false);
    const bias = biasConfig[card.smartMoneyBias];
    const BiasIcon = bias.icon;

    const pnlPos = (card.priceChangePct ?? 0) >= 0;

    return (
        <div className="rounded-2xl border border-white/[0.07] bg-[#0E1320] overflow-hidden shadow-xl shadow-black/30">
            {/* ── Card header ── */}
            <div className="relative px-5 py-4 overflow-hidden"
                style={{ background: 'linear-gradient(135deg, #0F1A2E 0%, #121B2F 50%, #0A1520 100%)' }}>
                <div className="absolute inset-0 opacity-30"
                    style={{ background: 'radial-gradient(ellipse at top left, rgba(59,246,138,0.08) 0%, transparent 60%)' }} />

                <div className="relative flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center">
                            <Crosshair className="h-4 w-4 text-emerald-400" />
                        </div>
                        <div>
                            <div className="flex items-center gap-2">
                                <span className="text-xl font-bold text-zinc-100 tracking-tight">{card.symbol}</span>
                                {card.isAutoGenerated && (
                                    <span className="px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-widest rounded bg-blue-500/20 text-blue-300 border border-blue-500/20">
                                        <Sparkles className="h-2.5 w-2.5 inline mr-0.5" />Auto
                                    </span>
                                )}
                            </div>
                            <div className="flex items-center gap-2 mt-0.5">
                                <span className="text-[11px] text-zinc-500 uppercase tracking-widest font-medium">
                                    Trade Pilot Setups
                                </span>
                            </div>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        {card.currentPrice && (
                            <div className="text-right">
                                <p className="text-lg font-bold font-mono text-zinc-100">${card.currentPrice.toFixed(2)}</p>
                                {card.priceChangePct !== undefined && (
                                    <p className={clsx('text-xs font-medium', pnlPos ? 'text-emerald-400' : 'text-rose-400')}>
                                        {pnlPos ? '+' : ''}{card.priceChangePct.toFixed(2)}%
                                    </p>
                                )}
                            </div>
                        )}
                        <div className="relative">
                            <button onClick={() => setMenuOpen(o => !o)}
                                className="p-1.5 rounded-lg text-zinc-600 hover:text-zinc-300 hover:bg-white/5 transition-colors">
                                <Edit3 className="h-4 w-4" />
                            </button>
                            {menuOpen && (
                                <>
                                    <div className="fixed inset-0 z-40" onClick={() => setMenuOpen(false)} />
                                    <div className="absolute right-0 top-full mt-1 w-40 rounded-xl border border-white/10 bg-[#1A1F2E] shadow-xl z-50 py-1">
                                        <button onClick={() => { setShowAddSetup(true); setMenuOpen(false); }}
                                            className="w-full px-4 py-2 text-left text-sm text-zinc-300 hover:bg-white/5 flex items-center gap-2">
                                            <Plus className="h-3.5 w-3.5" /> Add Setup
                                        </button>
                                        <div className="border-t border-white/5 my-1" />
                                        <button onClick={() => { deleteCard(card.id); setMenuOpen(false); }}
                                            className="w-full px-4 py-2 text-left text-sm text-rose-400 hover:bg-rose-500/10 flex items-center gap-2">
                                            <Trash2 className="h-3.5 w-3.5" /> Delete Card
                                        </button>
                                    </div>
                                </>
                            )}
                        </div>
                    </div>
                </div>

                {/* Bias + meta row */}
                <div className="relative mt-3 flex items-center gap-3 flex-wrap">
                    <div className={clsx('flex items-center gap-1.5 px-2.5 py-1 rounded-lg border text-xs font-semibold', bias.bg, bias.color)}>
                        <BiasIcon className="h-3 w-3" />
                        Smart Money: {bias.label}
                    </div>
                    <span className="text-[11px] text-zinc-600">·</span>
                    <div className="flex items-center gap-1 text-[11px] text-zinc-500">
                        <Clock className="h-3 w-3" />
                        {new Date(card.date + 'T00:00:00').toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' })}
                    </div>
                    {card.sessionNotes && (
                        <>
                            <span className="text-[11px] text-zinc-600">·</span>
                            <span className="text-[11px] text-zinc-500 italic">{card.sessionNotes}</span>
                        </>
                    )}
                </div>
            </div>

            {/* ── 3-column body ── */}
            <div className="grid grid-cols-3 divide-x divide-white/[0.05] min-h-[320px]">
                {/* Bullish */}
                <div className="px-4 py-4 flex flex-col">
                    <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center gap-1.5">
                            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                            <span className="text-[11px] font-bold uppercase tracking-widest text-emerald-400">Bullish Setups</span>
                        </div>
                        <button onClick={() => setShowAddSetup(true)}
                            className="text-zinc-700 hover:text-emerald-400 transition-colors p-0.5">
                            <Plus className="h-3.5 w-3.5" />
                        </button>
                    </div>
                    {card.bullishSetups.length === 0 ? (
                        <div className="flex-1 flex items-center justify-center">
                            <div className="text-center">
                                <TrendingUp className="h-7 w-7 text-zinc-800 mx-auto mb-2" />
                                <p className="text-xs text-zinc-700">No bullish setups</p>
                                <button onClick={() => setShowAddSetup(true)}
                                    className="mt-1.5 text-[11px] text-emerald-500/70 hover:text-emerald-400 transition-colors">Add one</button>
                            </div>
                        </div>
                    ) : (
                        <div className="flex-1 space-y-2 overflow-y-auto">
                            {card.bullishSetups.map(s => (
                                <SetupRow key={s.id} setup={s} cardId={card.id} currentPrice={card.currentPrice} />
                            ))}
                        </div>
                    )}
                </div>

                {/* Bearish */}
                <div className="px-4 py-4 flex flex-col">
                    <div className="flex items-center justify-between mb-3">
                        <div className="flex items-center gap-1.5">
                            <div className="w-1.5 h-1.5 rounded-full bg-rose-400" />
                            <span className="text-[11px] font-bold uppercase tracking-widest text-rose-400">Bearish Setups</span>
                        </div>
                        <button onClick={() => setShowAddSetup(true)}
                            className="text-zinc-700 hover:text-rose-400 transition-colors p-0.5">
                            <Plus className="h-3.5 w-3.5" />
                        </button>
                    </div>
                    {card.bearishSetups.length === 0 ? (
                        <div className="flex-1 flex items-center justify-center">
                            <div className="text-center">
                                <TrendingDown className="h-7 w-7 text-zinc-800 mx-auto mb-2" />
                                <p className="text-xs text-zinc-700">No bearish setups</p>
                                <button onClick={() => setShowAddSetup(true)}
                                    className="mt-1.5 text-[11px] text-rose-500/70 hover:text-rose-400 transition-colors">Add one</button>
                            </div>
                        </div>
                    ) : (
                        <div className="flex-1 space-y-2 overflow-y-auto">
                            {card.bearishSetups.map(s => (
                                <SetupRow key={s.id} setup={s} cardId={card.id} currentPrice={card.currentPrice} />
                            ))}
                        </div>
                    )}
                </div>

                {/* Key Levels */}
                <div className="px-4 py-4">
                    <KeyLevelsPanel card={card} />
                </div>
            </div>

            {showAddSetup && <AddSetupModal cardId={card.id} onClose={() => setShowAddSetup(false)} />}
        </div>
    );
}

// ─── Date Sidebar ─────────────────────────────────────────────────────────────

function DateSidebar({
    dates, selectedDate, onSelect, onNew,
    cardsByDate,
}: {
    dates: string[];
    selectedDate: string;
    onSelect: (d: string) => void;
    onNew: () => void;
    cardsByDate: Record<string, SetupCard[]>;
}) {
    const today = todayISO();
    const todayInList = dates.includes(today);

    return (
        <div className="w-[200px] flex-shrink-0 border-r border-white/5 bg-[#0C1018] flex flex-col h-full">
            {/* Header */}
            <div className="px-4 py-4 border-b border-white/5">
                <div className="flex items-center gap-2 mb-3">
                    <Calendar className="h-4 w-4 text-emerald-400" />
                    <span className="text-sm font-semibold text-zinc-200">Setups</span>
                </div>
                <button onClick={onNew}
                    className="w-full flex items-center justify-center gap-2 py-2 rounded-xl bg-emerald-500 text-[#181B24] font-semibold text-xs hover:bg-emerald-400 transition-all shadow-lg shadow-emerald-500/20">
                    <Plus className="h-3.5 w-3.5" /> New Setup Card
                </button>
            </div>

            {/* Date list */}
            <div className="flex-1 overflow-y-auto py-2">
                {/* Always show Today even if no cards */}
                {!todayInList && (
                    <button onClick={() => { onSelect(today); }}
                        className={clsx(
                            'w-full px-4 py-2.5 text-left transition-all border-l-2',
                            selectedDate === today
                                ? 'border-emerald-500 bg-emerald-500/10'
                                : 'border-transparent hover:bg-white/[0.03]'
                        )}>
                        <div className="flex items-center justify-between">
                            <span className={clsx('text-sm font-medium', selectedDate === today ? 'text-emerald-400' : 'text-zinc-500')}>
                                Today
                            </span>
                            <span className="text-[10px] text-zinc-700 bg-white/5 rounded px-1.5 py-0.5">0</span>
                        </div>
                        <p className="text-[10px] text-zinc-700 mt-0.5">
                            {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                        </p>
                    </button>
                )}

                {dates.map(date => {
                    const cards = cardsByDate[date] || [];
                    const isToday = date === today;
                    const isSelected = date === selectedDate;

                    return (
                        <button key={date} onClick={() => onSelect(date)}
                            className={clsx(
                                'w-full px-4 py-2.5 text-left transition-all border-l-2',
                                isSelected
                                    ? 'border-emerald-500 bg-emerald-500/10'
                                    : 'border-transparent hover:bg-white/[0.03]'
                            )}>
                            <div className="flex items-center justify-between">
                                <span className={clsx('text-sm font-medium', isSelected ? 'text-emerald-400' : 'text-zinc-400')}>
                                    {isToday ? 'Today' : formatDate(date)}
                                </span>
                                <span className={clsx(
                                    'text-[10px] rounded px-1.5 py-0.5 font-medium',
                                    isSelected ? 'bg-emerald-500/20 text-emerald-400' : 'text-zinc-600 bg-white/5'
                                )}>
                                    {cards.length}
                                </span>
                            </div>
                            <p className="text-[10px] text-zinc-700 mt-0.5">
                                {isToday ? new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : ''}
                                {cards.length > 0 && (
                                    <span className="ml-0.5">{cards.map(c => c.symbol).slice(0, 3).join(' · ')}{cards.length > 3 ? ' …' : ''}</span>
                                )}
                            </p>
                        </button>
                    );
                })}

                {dates.length === 0 && todayInList === false && (
                    <div className="px-4 py-8 text-center">
                        <p className="text-xs text-zinc-700">No setup history yet</p>
                    </div>
                )}
            </div>
        </div>
    );
}

// ─── Empty State ──────────────────────────────────────────────────────────────

function EmptyState({ onNew, date }: { onNew: () => void; date: string }) {
    const isToday = date === todayISO();
    return (
        <div className="flex-1 flex items-center justify-center p-12">
            <div className="text-center max-w-sm">
                <div className="w-16 h-16 rounded-2xl bg-white/[0.03] border border-white/5 flex items-center justify-center mx-auto mb-5">
                    <Crosshair className="h-8 w-8 text-zinc-700" />
                </div>
                <h2 className="text-lg font-semibold text-zinc-300 mb-2">
                    {isToday ? "No setups for today" : "No setups for this date"}
                </h2>
                <p className="text-sm text-zinc-600 mb-6 leading-relaxed">
                    {isToday
                        ? "Create a trade setup card for your watchlist tickers. Add bullish/bearish setups, key levels, and entry conditions."
                        : "No setup cards were logged for this date. Select another date or create a new one."}
                </p>
                <button onClick={onNew}
                    className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-500 text-[#181B24] font-semibold text-sm hover:bg-emerald-400 transition-all shadow-lg shadow-emerald-500/20">
                    <Plus className="h-4 w-4" /> New Setup Card
                </button>
                <div className="mt-6 flex flex-col gap-1.5 text-left">
                    {[
                        '📊 Pick a ticker (SPY, QQQ, NQ…)',
                        '📍 Add key support & resistance levels',
                        '🟢 Define bullish and bearish setups',
                        '✅ Check off entry conditions live',
                        '📈 Track which setups triggered',
                    ].map((s, i) => (
                        <p key={i} className="text-xs text-zinc-600">{s}</p>
                    ))}
                </div>
            </div>
        </div>
    );
}

// ─── Main Setups Page ─────────────────────────────────────────────────────────

export const Setups: React.FC = () => {
    const { cardsByDate, getDates, hydrate } = useSetupStore();
    const dates = getDates();
    const [selectedDate, setSelectedDate] = useState(todayISO());
    const [showCreate, setShowCreate] = useState(false);

    useEffect(() => { hydrate(); }, [hydrate]);

    const cardsForDate = cardsByDate[selectedDate] || [];

    return (
        <div className="h-full flex flex-col overflow-hidden" style={{ background: '#0A0E16' }}>
            {/* Top bar */}
            <div className="flex items-center justify-between px-5 py-3 border-b border-white/5 flex-shrink-0"
                style={{ background: '#0E1220' }}>
                <div className="flex items-center gap-3">
                    <Crosshair className="h-5 w-5 text-emerald-400" />
                    <div>
                        <h1 className="text-sm font-bold text-zinc-200">Pre-Market Setups</h1>
                        <p className="text-[11px] text-zinc-600">
                            {selectedDate === todayISO() ? "Today" : formatDate(selectedDate)} · {cardsForDate.length} card{cardsForDate.length !== 1 ? 's' : ''}
                        </p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <div className="flex items-center gap-1.5 px-2 py-1 rounded-lg bg-blue-500/10 border border-blue-500/20 text-[11px] text-blue-300">
                        <Sparkles className="h-3 w-3" />
                        Auto-generation coming soon
                    </div>
                    <button onClick={() => setShowCreate(true)}
                        className="flex items-center gap-2 px-3 py-2 rounded-xl bg-emerald-500 text-[#181B24] font-semibold text-xs hover:bg-emerald-400 transition-all shadow-md shadow-emerald-500/20">
                        <Plus className="h-3.5 w-3.5" /> New Card
                    </button>
                </div>
            </div>

            {/* Body */}
            <div className="flex-1 min-h-0 flex overflow-hidden">
                <DateSidebar
                    dates={dates}
                    selectedDate={selectedDate}
                    onSelect={setSelectedDate}
                    onNew={() => setShowCreate(true)}
                    cardsByDate={cardsByDate}
                />

                {/* Content */}
                <div className="flex-1 overflow-y-auto">
                    {cardsForDate.length === 0 ? (
                        <EmptyState onNew={() => setShowCreate(true)} date={selectedDate} />
                    ) : (
                        <div className="p-5 space-y-5">
                            {cardsForDate.map(card => <SetupCardView key={card.id} card={card} />)}
                        </div>
                    )}
                </div>
            </div>

            {showCreate && <CreateCardModal onClose={() => setShowCreate(false)} />}
        </div>
    );
};
